# Generated by Django 5.0.6 on 2024-06-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unias',
            new_name='manicura',
        ),
    ]
